# Artificial Intelligence - Fall 2020 - Laboratory 03:Python Introduction part III

c: Alexandra Dobrescu <alexandramaria.digital@gmail.com>

## Classes

The object-oriented programming paradigm in Python helps with structuring programs into `individual objects`. But how?

* An Object **O** from a class **C** has a set of properties **_p_** and actions **_a_**.

* The functions of a class are called `methods`. Their responsibility is to model the data corresponding to a given object.

* The objects of a class are known as `instances` and represent the source of collecting data.

```python

class EmptyClas:
    """
    This is a class without variables and methods
    """
    pass # The keyword pass is a placeholder


class MyClass:
    # A class variable
    name = 'My Class'
    
    def my_method(self, my_var):
        # An instance variable
        self.my_instance = my_var
```

In [33]:
class ScientificConference:
    """
    To define the properties of a class, 
    we use a special method called __init__.
    
    The special variable called "self"
    helps with associating the attributes
    w\ the new object: similar to `this`
    keyword from other programming languages
    and required to address variables from
    classes. 
    """
    def __init__(self, name, year, papers):
        """
        Establish the attributes of the
        class and assign values to the 
        corresponding parameters.
        """ 
        self.name = name
        self.year = year
        """
        b. Add new attribute `papers`
        """
        
        if papers==None :
            self.papers = {}
        else :
            self.papers = papers
    
    def add_manuscript(self, title, researcher):
        self.papers[researcher] = title

    def __str__(self):
        """
        To return the String representation of
        an object, we use the __str__ method. 
        """
        result = self.name + ' ' + str(self.year) + ': \n'
        for author, papers in self.papers.items():
            #result += f'{author}: {", ".join([str(paper) for paper in papers])} \n'
            result += author + ": " + papers + "\n"
        return result

### Task 0

**a.** Define two new `instances` of the `class ScientificConference` and return their representations.

Your output should look like:

`Proposals for ICML and NeurIPS conferences will be accepted until the end of November 2020.`

_Hint:_ `instance.attribute` helps you extracting a certain property.

In [34]:
# Your implementation here

conf1 = ScientificConference("ICML", 2020, None)
conf2 = ScientificConference("NeurIPS", 2020, None)

print(str(conf1))
print(str(conf2))

print("Proposals for " + conf1.name + " and " + conf2.name + " will be accepted until the end of November " + str(conf1.year) +".")

ICML 2020: 

NeurIPS 2020: 

Proposals for ICML and NeurIPS will be accepted until the end of November 2020.


**b.** Create a new attribute for the `class ScientificConference`, which is a dictionary passed as a parameter to the instances of the class and holds all of the papers of the conference.

_Note:_ You should check if `papers` is `None` in `__init__` and set it to `{}` instead.

_Please handle duplicate entries by removing them!_

**c.** Define the `add_manuscript` method which generates new entries in the dictionary described before. Please consider using the _researcher_ as a `key` and the _manuscript_ as `values`.

In [35]:
# Your implementation here
# Verify if your add_manuscript method works: add an item & print it

conf1.add_manuscript('Why I Do Not Like Bacon', 'Peppa Pig')
print(str(conf1))

ICML 2020: 
Peppa Pig: Why I Do Not Like Bacon



### Task 1

**a.** Define the class `Person` which stores the `title`, `name` and `surname` of a person.

The _tuple_ `allowed_titles` is a class variable which helps to verify if the title of a person is "Mr", "Mrs", "Ms", "Senior Researcher", "Professor of CS" or "Computer Scientist".

An error is returned if the title is not valid.

Use `__str__` defined below:

```python
    def __str__(self):
        return self.title + ' ' + self.surname + ' ' + self.name
```

In [194]:
# Your implementation here

class Person:
    allowed_titles = ['Mr', 'Mrs', 'Ms', 'Senior Researcher', 'Professor of CS', 'Computer Scientist']
    
    def __init__(self, title, name, surname) :
        a = 0
        for i in self.allowed_titles :
            if i == title :
                self.title = title
                a = 1
        if a == 0 :
            raise ValueError("Title not allowed.")
        self.name = name
        self.surname = surname
        
    def __str__(self):
        return self.title + " " + self.surname + " " + self.name

**b.** Create two instances of the class Person and verify if the following entries are valid:

* _Mr Ian Goodfellow_,
* _SeniorResearcher Tomas Mikolov._

In [51]:
# Your implementation here

pers0 = Person("Ms", "Peppa", "Pig")
print(pers0)
pers1 = Person("_Mr", "Ian", "Goodfellow_")
pers2 = Person("SeniorResearcher", "Thomas", "Mikolov")

Ms Pig Peppa


ValueError: Title not allowed.

### Task 2

In `ScientificConference` we have been using the paper parameter as a string, but this concept requires a detailed structure.

Introduce a new class, `Paper`, which has the following attributes:

* `authors`, 
* `title`, 
* `a_id`,
* `year`, 
* `status` (published or in development), 
* `peer_rating` (Excellent, Good, Fair, Poor, Barely Acceptable, Unacceptable).

In [202]:
class Paper:
    allowed_status = ['published', 'in development']
    allowed_peer_rating = ['Excellent', 'Good', 'Fair', 'Poor', 'Barely Acceptable', 'Unacceptable']
    
    def __init__(self, authors, title, a_id, status, year, peer_rating):
        self.authors = []
        self.authors.append(authors)
        self.title = title
        self.a_id = a_id
        self.year = year
        
        a = 0
        for i in self.allowed_status :
            if i == status :
                self.status = status
                a = 1
        if a == 0 :
            raise ValueError("Status value not allowed.")
        
        a = 0    
        for i in self.allowed_peer_rating :
            if i == peer_rating :
                self.peer_rating = peer_rating
                a = 1
        if a == 0 :
            raise ValueError("Peer rating value not allowed.")
        

    def __str__(self):
        author = self.authors[0]
        s = self.title + " by " + str(author) + " et al. (" + str(self.year) + "), a_id: " + str(self.a_id) + ", status: " + self.status + ", peer rating: " + self.peer_rating + "." 
        return s

## Inheritence

In Object-Oriented programming, this concept enables us to transfer the methods and the properties of a class to another class.

### Task 3

Create a class named `Researcher`, which inherits the properties and methods from the `Person` class. Besides, this class has an additional parameter, `papers` which is `None` by default.

_Note:_ You should check if `papers` is `None` in `__init__` and set it to `[]` instead.

```python
class Researcher(Person):
    def __init__('Add arguments'):
        super().__init__(title, name, surname)
```

In [196]:
# Define your first researcher
# Expected output: Senior Researcher Tomas Mikolov

class Researcher(Person) :
    def __init__(self, title, name, surname, papers) :
        super().__init__(title, name, surname)
        self.papers = papers
        if self.papers == None :
            self.papers = []
            self.co_authored = False
        else :
            self.co_authored = True
            
    def get_papers(self):
        for i in self.papers:
            print(i)
    
    def add_paper(self, p) :
        self.papers.append(p)
        self.co_authored = True
    
    # Task 4 b.
    
    def verify_co_authorship(self) :
        if (self.co_authored) :
            a = self.title + " " + self.name + " " + self.surname + " is a co-author.\n"
        else :
            a = self.title + " " + self.name + " " + self.surname + " is not a co-author.\n"
        print(a)
        
    # Task 4 c.
    
    def get_collab(self, j):
        for i in self.papers:
            if j in i.authors and self in i.authors:
                print(i)
                
res = Researcher("Senior Researcher", "Tomas", "Mikolov",None)
print(res)

Senior Researcher Mikolov Tomas


### Task 4

Consider the following scientists:

1.  Paper _Deep Learning_ published by Yann LeCun, Yoshua Bengio, Geoffrey Hinton, in _nature 521_, id = https://doi.org/10.1038/nature14539, peer_rating = Excelent.

2. Paper _On the difficulty of training recurrent neural networks_ by Razvan Pascanu, Tomas Mikolov, Professor of computer science Yoshua Bengio, in ICML 2013, id = https://arxiv.org/abs/1211.5063, peer_rating = Excelent.

2. Paper _Generative Adversarial Nets_ by Ian Goodfellow and Yoshua Bengio, NeurIPS 2015, id = http://papers.nips.cc/paper/5423-generative-adversarial-nets.pdf, peer_rating = Excelent.

3. Paper _Handwritten Digit Recognition with a Back-Propagation Network_ by Computer Scientist Yan LeCun, NeurIPS 1989, id =  https://papers.nips.cc/paper/293-handwritten-digit-recognition-with-a-back-propagation-network, peer_rating = Excelent.

4. Paper _Gated Softmax Classification_ by Geoffrey Hintorn, NeurIPS 2010, id = http://papers.neurips.cc/paper/3895-gated-softmax-classification, peer_rating = Good.

_Note:_ Let us consider "Mr" as a default title for the researchers without a specific caption. Also, for the id of a paper, please use only integers from the provided links.

**a.** Define the next 5 scientists and use them in your `paper` objects.



**b.** Create the `verify_co_authorship` function inside the `class Researcher` which checks if a certain researcher ever co-authored a paper.
_Hint:_ Use `self.co_authored = False` inside the `__init__` function.

**c.** Implement the `get_collab` function inside the `class Researcher` to discover the papers written by two researchers.

For instance, if Yoshua Bengio is researcher2 and Ian Goodfellow is researcher3, then:

`print_papers(researcher2.get_collab(researcher3))` should output:

_Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), a_id: 5423, status: published, rating: Excelent_

_Note:_ This function helps you to print the papers from a given list.

```python
def print_papers(paper_list):
    for paper in paper_list:
        print(paper)
```

**d.** What are the papers written by Yoshua Bengio?

Expected output:

`Deep Learning, Computer Scientist Yann LeCun et al. (2015), a_id: 14539, status: published, rating: Excelent`

`Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), a_id: 5423, status: published, rating: Excelent`

`Paper On the difficulty of training recurrent neural networks, Mr Razvan Pascanu et al. (2013), a_id: 5063, status: published, rating: Excelent`

**e.** Did he ever co-author a paper?

**f.** Which papers are published by Yann LeCun?

Expected output:

`Deep Learning, Computer Scientist Yann LeCun et al. (2015), a_id: 14539, status: published, rating: Excelent`

`Handwritten Digit Recognition with a Back-Propagation Network, Computer Scientist Yann LeCun et al. (1989), a_id: 293, status: published, rating: Good`

In [203]:
# a.
print("a")
res1 = Researcher("Computer Scientist","Yann","LeCun", None)
res2 = Researcher("Professor of CS","Yoshua","Bengio", None)
res3 = Researcher("Mr","Geoffrey","Hinton", None)
res4 = Researcher("Mr","Razvan","Pascanu", None)
res5 = Researcher("Mr","Ian","Goodfellow", None)

paper1 = Paper([res1,res2,res3],"Deep Learning",14539,"published",2020,"Excellent")
paper2 = Paper([res,res2,res4],"On the difficulty of training recurrent neural networks",1211,"in development",2013,"Excellent")
paper3 = Paper([res2,res5],"Generative Adversarial Nets",5423,"published",2015,"Excellent")
paper4 = Paper([res1],"Handwritten Digit Recognition with a Back-Propagation Network",293,"published",1989,"Excellent")
paper5 = Paper([res3],"Gated Softmax Classification",3895,"published",2010,"Excellent")

res1.add_paper(paper1)
res2.add_paper(paper1)
res3.add_paper(paper1)
res2.add_paper(paper2)
res4.add_paper(paper2)
res.add_paper(paper2)
res2.add_paper(paper3)
res5.add_paper(paper3)
res1.add_paper(paper4)
res3.add_paper(paper5)

# b.
print("b")
res1.verify_co_authorship()
res2.verify_co_authorship()

# c.
print("c")
res2.get_collab(res3)

# d.
print("d")
res2.get_papers()

# e.
print("e")
res2.get_collab(res3)

# f.
print("f")
res1.get_papers()

a
b
Computer Scientist Yann LeCun is a co-author.

Professor of CS Yoshua Bengio is a co-author.

c
d
Deep Learning by [<__main__.Researcher object at 0x0000010D9F95ED60>, <__main__.Researcher object at 0x0000010D9F990F40>, <__main__.Researcher object at 0x0000010D9F95E880>] et al. (2020), a_id: 14539, status: published, peer rating: Excellent.
On the difficulty of training recurrent neural networks by [<__main__.Researcher object at 0x0000010D9F985520>, <__main__.Researcher object at 0x0000010D9F990F40>, <__main__.Researcher object at 0x0000010D9F990820>] et al. (2013), a_id: 1211, status: in development, peer rating: Excellent.
Generative Adversarial Nets by [<__main__.Researcher object at 0x0000010D9F990F40>, <__main__.Researcher object at 0x0000010D9F990670>] et al. (2015), a_id: 5423, status: published, peer rating: Excellent.
e
f
Deep Learning by [<__main__.Researcher object at 0x0000010D9F95ED60>, <__main__.Researcher object at 0x0000010D9F990F40>, <__main__.Researcher object at

### Task 5 - Homework

Consider an updated version of the `ScientificConference` class, which should have a modified version of the function `add_manuscript`.

Use the `status` and the `peer_rating` variables as a **threshold** to add papers in your `papers` dictionary. The conferences will only be accepting `Excelent` papers. For this case, the dictionary has the year of the paper as `key`, and the `values` are stored as a tuple of `(researcher, manuscript)`. For the papers which don't satisfy this condition, the message _"Please review your submission."_ is displayed.

For papers submitted in 2015, when printing the conference, the `str` function should output:

```
NeurIPS 2020: 
2015: 
Mr Ian Goodfellow: Generative Adversarial Nets, Mr Ian Goodfellow et al. (2015), id: 5423, status: published, rating: Excelent 
Computer Scientist Yann LeCun: Deep Learning, Computer Scientist Yann LeCun et al. (2015), id: 14539, status: published, rating: Excelent
```

In [210]:
class ScientificConferenceUpdate:
    """
    To define the properties of a class, 
    we use a special method called __init__.
    
    The special variable called "self"
    helps with associating the attributes
    w\ the new object: similar to `this`
    keyword from other programming languages
    and required to address variables from
    classes. 
    """
    def __init__(self, name, year):
        """
        Establish the attributes of the
        class and assign values to the 
        corresponding parameters.
        """ 
        self.name = name
        self.year = year
        self.papers = {}
    
    def add_manuscript(self, manuscript, researcher):
        if manuscript.status=="published" and manuscript.peer_rating=="Excellent" :
            self.papers[manuscript.year] = (researcher, manuscript)
        else :
            print("Please review your submission.")
        
    def __str__(self):
        """
        To return the String representation of
        an object, we use the __str__ method. 
        """
        result = self.name + ' ' + str(self.year) + ': \n'
        for year, papers in self.papers.items():
            result += f'{year}: \n'
            for (author, paper) in papers: 
                result += f'{str(author)}: {paper} \n'
        return result

In [211]:
conf = ScientificConferenceUpdate("NeurIPS", 2020)
conf.add_manuscript(paper3,res5)
conf.add_manuscript(paper1,res1)
print(conf)

TypeError: cannot unpack non-iterable Researcher object

In [206]:
print("This was hard. Couldn't do it. Sorry. Liked the presentations during lab, though.")

This was hard. Couldn't do it. Sorry. Liked the presentations during lab, though.
